### PR TITLE
Update to the DB schema to support chains of trust

### PR DESCRIPTION
**Pull request by jvehent**
This schema should support multiple chain of trusts per certificate, as well as updating the status of a chain of trust over time.
schema

r? @0xDiBa @marumari

### CODE REVIEW

**Comment by marumari** [comment]
I'm a bit skeptical on all the trusted_ fields; are those going to be regenerated constantly?

Also, shouldn't the scan be saying which trust chain that it used at the time of the scan?

**Comment by jvehent** [comment]
> I'm a bit skeptical on all the trusted_ fields; are those going to be regenerated constantly?

The scanner will rerun the tests and only store a new row in the `trust` table if the results are different from the current row. So, yes, the data is regenerated constantly but no it isn't stored in database as long as it doesn't change.

> Also, shouldn't the scan be saying which trust chain that it used at the time of the scan?

That's a good point. I'll add a field.

**Comment by jvehent** [comment]
Schema updated with the reference to the chain of trust used.
schema

**Comment by marumari** [comment]
That looks a lot better to me.  I'm just questioning if we need to even have the trusted_ fields at all?  Surely when we view a single certificate, we can just run the trusted tests then?  I can only really see it useful to store if we're running big queries constantly against those fields.

I guess honestly it's not a big deal either way, since it's just a boolean.  :)

In any case, r+.

**Comment by jvehent** [comment]
The motivation behind storing the truststore validation is to analyze the impact of a truststore update on certificates, before and after the change. Without storing those fields, we would need to keep versions of each truststore and rerun the validation against all of them. I think it's worth storing that data, giving it's just a few booleans. 

Not that we may still need to store versions of truststore in DB anyway. That's probably the next thing to add to the schema, but it's not a blocker to move forward on the current issue.

**Comment by 0xDiBa** [comment]
I think that eventually, and for "research" purposes, we are going to derive current truststore versions from the in_xxx_root_store variables of CA certificates. Coming to the point of storing versions of each truststore will help us get a historical overview of certificates in truststores.

I think we are good to go ( and merge ) for now.

**Pull request merged**
